services:
  bot:
      build: ./
      environment:
        - BOT_TOKEN=${BOT_TOKEN}
        - ADMIN_TELEGRAM_ID=${ADMIN_TELEGRAM_ID}
        - LOG_LEVEL=${LOG_LEVEL}
        - JSON_LOGS=&{JSON_LOGS}
      command: sh -c ". .venv/bin/activate && python -m yt_playlist_bot"